#default by: 'id'
advertiser_list_page:
    url: 'advertisers/'
    search_box:
        value: 'filter_advertisers'
    new_advertiser:
        by: 'css selector'
        value: '.lnkbtn.add>span'
    advertiser_name_link:
        by: 'css selector'
        value: 'tbody > tr:nth-child(1) > td:nth-child(1) > a'
    edit_icon:
        by: 'css selector'
        value: 'img[alt="Icon_edit"]'
    delete_icon:
        by: 'css selector'
        value: 'img[alt="Icon_remove"]'
    sort_name_column:
        by: 'css selector'
        value: '.sortable.name_link.header'
    sort_status_column:
        by: 'css selector'
        value: '.sortable.status.header'
    sort_agency_column:
        by: 'css selector'
        value: '.sortable.agency.header'
    page_header:
        by: 'css selector'
        value: '.box.header-text'
    success_message_locator:
        by: 'css selector'
        value: '.flash.notice'
    advertiser_list:
        by: 'css selector'
        value: '#advertisers_table > .sortable > tbody'
    success_message: "Advertiser ‘{0}’ was successfully created."
    delete_message: "Advertiser '{0}' successfully deleted."
    list_page_contents: ['search_box', 'new_advertiser', 'sort_name_column', 'sort_status_column', 'sort_agency_column']
    advertiser_list_page_title: 'Advertisers'
