new_advertiser:
    url: 'advertisers/new/'
    agency_group:
        value: 'agency_group_id'
    agency:
        value: 'agency_id'
    organization_name:
        value: 'advertiser_name'
    primary_domain:
        value: 'advertiser_primary_domain'
    create_advertiser:
        value: 'advertiser_submit'
    email:
       value: 'advertiser_organization_attributes_email'
    contact_name:
       value: 'advertiser_organization_attributes_contact_name'
    additional_domains:
       value: 'advertiser_additional_domains'
    offer_type:
       value: 'advertiser_offer_type_id'
    platform_type:
       value: 'advertiser_platform_type'
    one_impression_per_page:
       value: 'advertiser_one_impression_per_page'
    disabled_currency_drop_down:
       by: 'css selector'
       value: 'select[id="advertiser_organization_attributes_currency_id"][disabled="disabled"]'
    select_all_currency:
       value: 'select_all'
    cogs_inherited_checkbox:
       value: "advertiser_organization_attributes_cogs_inherited"
    cogs_textbox:
       value: 'advertiser_organization_attributes_cogs'
    margin_inherited_checkbox:
       value: 'advertiser_organization_attributes_margin_inherited'
    margin_textbox:
       value: 'advertiser_organization_attributes_margin'
    oba_checkbox:
       value: 'advertiser_organization_attributes_oba_enabled'
    oba_section:
       value: 'oba_compliance'
    oba_popup:
        by: 'css selector'
        value: 'div[aria-labelledby$="oba-warning"]'
    oba_popup_accept_button:
        by: 'css selector'
        value: '#oba-warning~div>button:nth-child(1)>span'
    oba_popup_cancel:
        by: 'css selector'
        value: '#oba-warning~div>button:nth-child(2)>span'
    rate_card:
       value: 'advertiser_rate_card'
    new_add_on_cost:
       value: 'new_add_on_cost'
    add_on_cost_fee_type:
       by: 'css selector'
       value: '.aoc_fee_type > select'
    add_on_cost_value:
       by: 'css selector'
       value: '.aoc_value > input'
    add_on_cost_name:
       by: 'css selector'
       value: '.aoc_name > input'
    submit_button:
       value: 'advertiser_submit'
    cancel_button:
       by: 'css selector'
       value: 'input[type="button"][value="Cancel"]'
    inherit_licensing_checkbox:
       value: 'inherit_licensing'
    cost_model_type:
       value: 'advertiser_organization_attributes_campaign_cost_model_type_ids_1'
    add_on_cost_billable_checkbox:
       by: 'css selector'
       value: '.aoc_is_billable > input[type="checkbox"]'
    add_on_cost_marketplace_checkbox:
       by: 'css selector'
       value: '.aoc_is_marketplace > input[type="checkbox"]'
    online_media_type_checkbox:
       online:
           by: 'id'
           value: 'advertiser_organization_attributes_online_enabled'
       mobile:
           by: 'id'
           value: 'advertiser_organization_attributes_mobile_enabled'
       video:
           by: 'id'
           value: 'advertiser_organization_attributes_video_enabled'
    select_all_inventories:
       value: 'select_all_inventories'
    geo_targeting_checkbox:
       value: 'advertiser_organization_attributes_global_geo_targeting'
    insights:
       frequency:
           by: 'id'
           value: 'advertiser_organization_attributes_aag_frequency_impact'
       consideration:
           by: 'id'
           value: 'advertiser_organization_attributes_aag_consideration_period'
       retargeting:
           by: 'id'
           value: 'advertiser_organization_attributes_aag_retarget_effect'
       index:
           by: 'id'
           value: 'advertiser_organization_attributes_aag_best_metrocodes_index'
    add_on_cost_dataxu_controlled_checkbox:
       by: 'css selector'
       value: '.aoc_is_locked > input[type="checkbox"]'
    add_on_cost_channel:
       by: 'css selector'
       value: '.aoc_channel > select'
    remove_add_on_cost:
       by: 'css selector'
       value: '.remove_add_on_cost'
    add_on_cost_modified_pop_up:
       pop_up:
           by: 'css selector' 
           value: '#add-on-costs-modified-dialog-confirm'
       accept: 
           by: 'css selector'
           value: '#add-on-costs-modified-dialog-confirm ~ div > button:nth-child(2)'
       cancel:
           by: 'css selector'
           value: '#add-on-costs-modified-dialog-confirm ~ div > button:nth-child(1)'
    organization_type:
           by: 'css selector'
           value: 'select[id="organization_type"][disabled="disabled"]'
    agency_grayed_out:
           by: 'css selector'
           value: 'select[id="agency_id"][disabled="disabled"]'
    agency_group_grayed_out:
           by: 'css selector'
           value: 'select[id="agency_group_id"][disabled="disabled"]'
    attributes:
         organization_name: ''
         email: ''
         contact_name: ''
         add_on_cost_value: ''
         add_on_cost_name: ''
         rate_card: ''
         primary_domain: ''
    cogs_currency:
        by: 'css selector'
        value: '.currency_iso_code'
    add_on_cost_section_headers:
        name:
            by: 'css selector'
            value: 'label[for="advertiser_aoc_name"]'
        cpm:
            by: 'css selector'
            value: 'label[for="advertiser_aoc_value"]'
        billable:
            by: 'css selector'
            value: 'label[for="advertiser_aoc_is_billable"]'
        channel:
            by: 'css selector'
            value: 'label[for="advertiser_channel"]'
    advertiser_invenotry_supplier_label:
        by: 'css selector'
        value: '#inventory_suppliers > div:nth-child(1)> label'
    configure_seats_pop_up:
        pop-up:
            by: 'css selector'
            value: 'div[class*="ui-dialog ui-widget ui-widget-content ui-corner-all modal-dialog"][style*="display: block;"]'
        inherit_checkbox:
            by: 'css selector'
            value: 'div[class*="ui-dialog ui-widget ui-widget-content ui-corner-all modal-dialog"][style*="display: block;"] > div:nth-child(2) > form > .group > .cols4 > .inherit_button_div > .first_seat_row'
        override_checkbox:
            by: 'css selector'
            value: 'div[class*="ui-dialog ui-widget ui-widget-content ui-corner-all modal-dialog"][style*="display: block;"] > div:nth-child(2) > form > .group > .cols4 > .override_button_div > .first_seat_row'
        seat_name:
            by: 'css selector'
            value: 'div[class*="ui-dialog ui-widget ui-widget-content ui-corner-all modal-dialog"][style*="display: block;"] > div:nth-child(2) > form > .credential_fields > .seat_container > div > div:nth-child(1) > input'
        seat_id:
            by: 'css selector'
            value: 'div[class*="ui-dialog ui-widget ui-widget-content ui-corner-all modal-dialog"][style*="display: block;"] > div:nth-child(2) > form > .credential_fields > .seat_container > div > div:nth-child(2) > input'
        seat_billable:
            by: 'css selector'
            value: 'div[class*="ui-dialog ui-widget ui-widget-content ui-corner-all modal-dialog"][style*="display: block;"] > div:nth-child(2) > form > .credential_fields > .seat_container > div > div:nth-child(3) > input ~ input'
        ok_button:
            by: 'css selector'
            value: 'div[class*="ui-dialog ui-widget ui-widget-content ui-corner-all modal-dialog"][style*="display: block;"] > div:nth-child(3) > button[id *="ok_button"]'
        cancel_button:
            by: 'css selector'
            value: 'div[class*="ui-dialog ui-widget ui-widget-content ui-corner-all modal-dialog"][style*="display: block;"] > div:nth-child(3) > button[id *="cancel_button"]'
        add_seat:
            by: 'css selector'
            value: 'div[class*="ui-dialog ui-widget ui-widget-content ui-corner-all modal-dialog"][style*="display: block;"] > div:nth-child(2) > form > .cols2 > button'
        remove_seat:
            by: 'css selector'
            value: 'div[class*="ui-dialog ui-widget ui-widget-content ui-corner-all modal-dialog"][style*="display: block;"] > div:nth-child(2) > form > .credential_fields > .seat_container > div > .remove_seat'
        seat_content:
            by: 'css selector'
            value: 'tr > td:nth-child(2) >div>label'
    edit_configure_seat:
            by: 'css selector'
            value: 'img[alt="Icon_edit"]'
    google_adx_seat_edit_icon:
        by: 'css selector'
        value: '#google_creds_edit>img'
    error_message_locator: "#errorExplanation > ul> li"
    euro_currency_checkbox:
           value: 'advertiser_organization_attributes_currency_ids_3'
    insight_list: [ 'Frequency Impact Report', 'Consideration Period Report', 'Retargeting Effectiveness Report', 'Index of Best Metrocodes']
    online_disabled_checkbox:
           by: 'css selector'
           value: 'input[id="advertiser_organization_attributes_online_enabled"][disabled="disabled"]'
    disabled_select_all_inventory_checkbox:
           by: 'css selector'
           value: 'input[id="select_all_inventories"][disabled="disabled"]'
    green_tick:
         by: 'css selector'
         value: '.cols9>ul>li>img ~ input[value="{0}"]'
    selected_currency:
         by: 'css selector'
         value: '.cols9>ul>li>img ~ input'
    inventory_select: "input[data-inventory_supplier_name='{0}']"
    configure_seat_section:
        inventory_supplier:
            by: 'css selector'
            value: '#organization_seats_content > table > thead > tr > th:nth-child(1)'
        seat:
            by: 'css selector'
            value: '#organization_seats_content > table > thead > tr > th:nth-child(2)'
        currency:
            by: 'css selector'
            value: '#organization_seats_content > table > thead > tr > th:nth-child(3)'
        billable_media:
            by: 'css selector'
            value: '#organization_seats_content > table > thead > tr > th:nth-child(4)'
    seat_names_locator:
        by: 'css selector'
        value: '.supplier_label'
    error_message_for_blank:
            add_on_cost_cpm: "Organization add on costs value is not a number"
            add_on_cost_name: "Organization add on costs name can't be blank"
            advertiser_name: "Name Advertiser name cannot be blank."
    error_message_for_260_characters:
            rate_card: "Rate card currency line 2: Geographic,1.0,0.45,0.54,PLN must match the organization currency (USD)."
            add_on_cost_cpm: "Organization add on costs value Value must be less than or equal to 100 USD."
            add_on_cost_name: "Organization add on costs name is too long (maximum is 255 characters)"
            advertiser_name: "Name is too long (maximum is 255 characters)"
            email: "Organization email is too long (maximum is 255 characters)"
            contact_name: "Organization contact name is too long (maximum is 255 characters)"
    error_message_for_special_char:
           margin: "Organization margin is not a number"
           contact_name: "Organization contact name cannot contain special characters"
           email: 'Organization email must be in a valid format.'
    error_message_for_html_tag:
           cogs: "Organization cogs must be greater than or equal to 0"
           margin: "Organization margin must be greater than or equal to 0"
           contact_name: "Organization contact name cannot contain special characters"
           email: 'Organization email cannot contain special characters'
           advertiser_name: "Name is invalid"
    error_message_for_alphanumeric:
           cogs: "Organization cogs is not a number"
           margin: "Organization margin is not a number"
    cogs_more_than_10: 'Organization cogs Value must be less than or equal to 10 USD.'
    margin_more_than_100: 'Organization margin must be less than 100'
    add_on_cost_cpm_more_than_100: "Organization add on costs value Value must be less than or equal to 100 USD."
    add_on_cost_headers: ['name', 'cpm', 'billable', 'channel']
    add_on_cost_controls: ['add_on_cost_name', 'add_on_cost_value', 'add_on_cost_billable_checkbox', 'add_on_cost_channel', 'remove_add_on_cost']
    grayed_out_controls: ['organization_type', 'agency_grayed_out']
    grayed_out_field: ['inherit_licensing_checkbox', 'online_disabled_checkbox', 'disabled_select_all_inventory_checkbox']
    inherit_value_controls : ['online_disabled_checkbox', 'disabled_select_all_inventory_checkbox']
    media_types: ['online', 'mobile', 'video']
    configure_seat_controls: ['inventory_supplier', 'seat', 'currency', 'billable_media']
    oba_controls: ['oba_section', 'oba_checkbox']
    oba_message: ['Enabled OBA compliance for all campaigns', 'The AdChoices icon indicates that the advertising is covered by the OBA self-regulatory program, and by clicking on it consumers will be able to click to a clear disclosure statement regarding the data collection and use practices associated with the ad, as well as an easy-to-use opt-out mechanism.']
    configure_seat_pop_up: ['inherit_checkbox', 'override_checkbox', 'ok_button', 'cancel_button']
    one_view_section:
      section_locator:
          by: 'id'
          value: 'organization_oneview_policies'
      policies_table:
          by: 'css selector'
          value: '.cols11>table'
      data_policy_text:
          by: 'css selector'
          value: '.cols11>table>tbody > tr:nth-child({0}) > td:nth-child(3)'
      column_headers:
          by: 'css selector'
          value: '.cols11>table>thead>tr>th:nth-child({0})'
      lock_policy_checkbox:
          by: 'id'
          value: 'lock-default-policy-selection'
      single_policy_default_checked_checkbox:
          by: 'css selector'
          value: 'input[id="oneview_policy_1"][disabled="disabled"][checked="checked"]'
      high_precision_policy_checkbox:
          by: 'id'
          value: 'oneview_policy_2'
      broad_reach_policy_checkbox:
          by: 'id'
          value: 'oneview_policy_3'
      policy_radio_buttons:
          by: 'css selector'
          value: '.cols11>table>tbody > tr:nth-child({0}) > td:nth-child(2) > input'
    dataxu_logo:
       by: 'css selector'
       value: '#logo>img'
    create_advertiser_page_title: 'Create New Organization'
