#default by: 'id'
agency_group_list:
    url: 'agency_groups/'
    new_agency_group_link:
        by: 'link text'
        value: 'New Agency Group'
    search_box:
        value: 'filter_agency_groups'
    page_header:
        by: 'css selector'
        value: '.box.header-text'
    edit_icon:
        by: 'css selector'
        value: "a[title='Edit']"
    delete_icon:
        by: 'css selector'
        value: "a[title='Delete']"
    success_message: 'Agency group "{0}" successfully deleted.'
    success_message_locator:
        by: 'css selector'
        value: '.flash.notice'
    invalid_search_message: 'No Agency Groups to browse.'
    agency_group_name_locator:
        by: 'css selector'
        value: 'tbody > tr:nth-child(1) >td:nth-child(1) > a'
    sort_button_locator:
        by: 'css selector'
        value: '.sortable.name_link.header'
    agency_group_list_table:
        by: 'css selector'
        value: '#agency_groups_table > .sortable > tbody'
    agency_group_list_page_title: 'Agency Groups'
