agency_details_page:
    agency_list_page_link:
        by: 'css selector'
        value: '.headBot>p>a'
    agency_group_link:
        by: 'css selector'
        value: '.cols3>a'
    advertiser_list:
        by: 'css selector'
        value: '.cols3>ul>li>a'
    add_advertiser_button:
        by: 'css selector'
        value: '.add.button'
    edit_details_button:
        by: 'css selector'
        value: 'input[value="Edit Details"]'
    details_section:
        value: 'details'
    currencies_section:
        value: 'currencies'
    settings_section:
        value: 'settings'
    add_on_cost_section:
        value: 'add_on_costs'
    rate_card_section:
        value: 'segment_rates'
    licenses_section:
        value: 'licenses'
    private_inventory_section:
        value: 'inventories'
    seats_section:
        value: 'seats'
    details_section_elements:
        organization_type:
            by: 'css selector'
            value: '#details_content > div:nth-child(1) > div > strong'
        organization_name:
            by: 'css selector'
            value: '#details_content > div:nth-child(2) > div:nth-child(1) > strong'
        email:
            by: 'css selector'
            value: '#details_content > div:nth-child(2) > div:nth-child(2) > strong'
        agency_group: 
            by: 'css selector'
            value: '#details_content > div:nth-child(3) > div:nth-child(1) > strong'
        advertiser:
            by: 'css selector'
            value: '#details_content > div:nth-child(3) > div:nth-child(2) > strong'
    cogs_value:
        by: 'css selector'
        value: '.cogs'
    margin_value:
        by: 'css selector'
        value: '.margin'
    add_on_cost_rate:
        by: 'css selector'
        value: '.cols1.aoc_value.rgt.break-word'
    add_on_cost_name:
        by: 'css selector'
        value: '.cols3.aoc_name.break-word'
    seat_content:
        by: 'css selector'
        value: 'tr > td:nth-child(2) > div'
    google_adx_seat:
        by: 'css selector'
        value: '.google_seat_name.seat_content>div'
    google_content_network_seat:
        by: 'css selector'
        value: '.google_contentnetwork_seat_name.seat_content>div'
    agency_facebook_seat_value:
        by: 'css selector'
        value: '.facebook_rtb_seat_name.seat_content > div'
    success_message:
        organization_name:
            create_new_agency: 'Agency {0} was successfully created.'
    agency_show_page_title: 'Agency {0}'
    get_advertiser_name_from_link:
       by: 'xpath'
       value: "//div[@class='cols3']/ul/li/a[starts-with(text(), '%s')]"
