#default by: 'id'
admin_page:
    url: 'account?locale=en'
    dataxu_logo:
       by: 'css selector'
       value: '#logo>img'
    link_sections:
        by: 'css selector'
        value: '.account_groups'
    admin_link:
        by: 'link text'
        value: 'Admin'
    edit_my_account_link:
        by: 'link text'
        value: 'Edit My Account'
    subscriptions_link:
        by: 'link text'
        value: 'Subscriptions'
    report_inbox_link:
        by: 'link text'
        value: 'Report Inbox'
    create_new_campaign_link:
        by: 'link text'
        value: 'Create New Campaign'
    inventory_link:
        by: 'css selector'
        value: '.account_groups > div:nth-child(2) > ul > li:nth-child(2) > a'
    creative_link:
        by: 'css selector'
        value: '.account_groups > div:nth-child(2) > ul > li:nth-child(3) > a'
    segments_link:
        by: 'css selector'
        value: '.account_groups > div:nth-child(2) > ul > li:nth-child(4) > a'
    users_link:
        by: 'css selector'
        value: '.account_groups > div:nth-child(4) > ul > li:nth-child(1) > a'
    create_new_user_link:
        by: 'link text'
        value: 'Create New User'
    business_intelligence_reports_link:
        by: 'link text'
        value: 'Business intelligence reports'
    customer_intelligence_dataset_link:
        by: 'link text'
        value: 'Customer intelligence dataset'
    product_feature_link:
        by: 'link text'
        value: 'Product features'
    product_feature_list_table:
        value: 'product_features_view_table'
    login_screen_slides_link:
        by: 'link text'
        value: 'Login screen slides'
    ad_server_tag_versions_link:
        by: 'link text'
        value: 'Ad server tag versions'
    system_message_table:
        value: 'system_notice_table'
    system_message_popup:
        by: 'css selector'
        value: '.ui-dialog'
    system_message_close:
        by: 'css selector'
        value: '.ui-icon-closethick'
    agency_group_link:
        by: 'css selector'
        value: '.account_groups > div:nth-child(3) > ul > li:nth-child(1) > a'
    agencies_link:
        by: 'css selector'
        value: '.account_groups > div:nth-child(3) > ul > li:nth-child(2) > a'
    advertiser_link:
        by: 'css selector'
        value: '.account_groups > div:nth-child(3) > ul > li:nth-child(3) > a'
    display_message_link:
        value: 'display_notices'
    dismiss_all_notices_button:
        by: 'css selector'
        value: '.dismiss_all_notices'
    system_message_table:
        by: 'css selector'
        value: '.sortable.selectable'
    admin_page_title: 'Administration'
    subscriptions_table_header: ['Description', 'Email', 'Frequency', 'Created On', 'Actions']
    admin_page_contents_by_role:
        inventory_manager:
            title: 'Administration'
            edit_my_link: 'Edit My Account'
            report_inbox: 'Report Inbox'
            inventory_link: 'Inventory'
            segments: 'Segments'
            agency_groups: 'Agency Groups'
            agencies: 'Agencies'
            advertisers: 'Advertisers'
            user: 'User'
    permitted_to_create_campaign: 'Create New Campaign'
    permitted_to_create_creative: 'Creative'
    permitted_to_create_user: 'Create New User'
    permitted_to_create_reports: 'Business intelligence reports'
    permitted_to_product_feature: 'Product features'
    permitted_to_login_slide: 'Login Screen Slides'
    permitted_to_audience: 'Audience'
    permitted_to_activity: 'Activity'
    permitted_to_inventory: 'Inventory'
    activity_tab:
        value: 'ql_activities'
    audience_tab:
        value: 'ql_audiences'
    inventory_tab:
        value: 'ql_inventory'
