#default by: 'id'
user_show_page:
    edit_link:
        by: 'link text'
        value: 'Edit'
    first_assigned_organization_under_roles:
        by: 'css selector'
        value: '#roles_and_permissions_content > div:nth-child(2) > div'
    user_creation_success_message: 'New User Account registered successfully.'
    user_update_message: 'User Account updated!'
