#default by: 'id'
user_edit_page:
    email_text_box:
        value: 'user_email'
    add_user_role_button:
        by: 'css selector'
        value: '.add'
    organization_dropdown:
        value: 'user_organization_id'
    roles_and_permissions_organization_dropdown:
        by: 'css selector'
        value: "select[id$='_scope_id']"
    roles_and_permissions_role_dropdown:
        by: 'css selector'
        value: "select[id$='_auth_role_id']"
    roles_and_permissions_remove_button:
        by: 'css selector'
        value: "img[alt='Delete']"
    submit_button:
        value: 'user_submit'
    user_edit_page_title: 'Edit User'
