#default by: 'id'
user_list_page:
    url: 'users/'
    filter:
        value: 'filter_users'
    first_user_email:
        by: 'css selector'
        value: 'table > tbody > tr:nth-child(1) > td:nth-child(1) > a'
    first_user_edit_icon:
        by: 'css selector'
        value: 'tbody > tr:nth-child(1) > td > a > img'
    list_pagination_setup:
        by: 'css selector'
        value: '.pagination'
    new_user_button:
        by: 'css selector'
        value: '.add.button'
    campaign_manager: 'dx_campaign'
    campaign_manager_email:
        by: 'link text'
        value: 'dx_campaign@dataxu.com'
    inventory_manager: 'dx_inventory'
    inventory_manager_email:
        by: 'link text'
        value: 'dx_inventory@dataxu.com'
    campaign_manager_with_one_view: 'dx_oneview_campaign'
    campaign_manager_with_one_view_email:
        by: 'link text'
        value: 'dx_oneview_campaign@dataxu.com'
    non_dataxu_domain_campaign_user: 'dx_non'
    non_dataxu_domain_campaign_user_email:
        by: 'link text'
        value: 'dx_non@domain.com'
    user_list_page_contents: ['Users', 'Email', 'Organization', 'Roles', 'Status', 'Actions']
