#default by: 'id'
create_flight:
    error_div:
        by: 'css selector'
        value: '.flash.error'
    campaign_name_link:
        by: 'css selector'
        value: '.breadcrumbs > a:nth-child(2)'
    edit_flight_name:
        value: 'flight_description'
    flight_tactic:
        value: 'flight_tactic_id'
    selected_flight_type:
        by: 'css selector'
        value: '#flight_details_content > div:nth-child(2) > div:nth-child(2)'
    media_type:
        value: 'flight_creative_format_id'
    algorithm:
        by: 'css selector'
        value: '.chzn-single'
    selected_algorithm:
        by: 'css selector'
        value: '.chzn-single > span'
    start_date:
        value: 'flight_start_at_visible'
    end_date:
        value: 'flight_end_at_visible'
    spent:
        by: 'css selector'
        value: '#flight_spent_input>input'
    default_bid_usd:
        value: 'flight_default_bid'
    budget_usd:
        value: 'flight_io_budget'
    alloc:
        value: 'flight_percent_allocated'
    inventory_suppliers:
        by: 'css selector'
        value: '#inventory_suppliers>div>h1>div>a>.icon-information'
    select_inventory:
        by : 'css selector'
        value: '#inventory_suppliers_all :first-child'
    avail_inventory:
        value: 'inventory_suppliers_all'
    move_select_inventory:
        value: 'mv_sel_inventory_suppliers'
    move_all_inventory:
        value: 'mv_all_sel_inventory_suppliers'
    remove_all_inventory:
        value: 'rm_all_sel_inventory_suppliers'
    remove_select_inventory:
        value: 'rm_sel_inventory_suppliers'
    applied_inventory:
        value: 'inventory_suppliers_selected'
    device_types:
        by: 'css selector'
        value: '#device_types>div>h1>div>span'
    inherit_device_types:
        value: 'flight_inherit_device_types_true'
    separate_device_types:
        value: 'flight_inherit_device_types_false'
    devices_available:
        value: 'device_types_device_types_all'
    move_selected_devices:
        value: 'mv_sel_device_types_device_types'
    remove_selected_devices:
        value: 'rm_sel_device_types_device_types'
    move_all_selected_devices:
        value: 'mv_all_sel_device_types_device_types'
    remove_all_selected_devices:
        value: 'rm_all_sel_device_types_device_types'
    devices_selected:
        value: 'device_types_device_types_selected'
    deals:
        by: 'css selector'
        value: '#deal_inventory>div>h1>div>span'
    deals_filters:
        by: 'css selector'
        value: '#deal_inventory_filter>label>input'
    deals_table:
        by: 'css selector'
        value: '.dataTable'
    master_select_deals:
        value: 'select_all_deal_inventory'
    select_first_deal:
        by: 'css selector'
        value: '#deal_inventory > tbody > tr:nth-child(1) > td >input[type="checkbox"]'
    first_deal:
        by: 'css selector'
        value: '#deal_inventory > tbody > tr:nth-child(1) > td > a'
    add_on_cost_expand:
        by: 'css selector'
        value: '#add_on_costs>div>h1>div>span'
    new_add_on_cost:
        value: 'add_new_add_on_cost'
    add_on_cost_name:
        by: 'css selector'
        value: 'select[id$="_name"]'
    add_on_cost_rate:
        by: 'css selector'
        value: 'input[type="number"][id$="_value"]'
    add_on_cost_name_second:
        by: 'css selector'
        value: '.aoc_row:nth-child(6) > .aoc_name > .custom_select > select'
    add_on_cost_custom:
        by: 'css selector'
        value: '.aoc_row:nth-child(3) > .aoc_name > .custom_select > input'
    add_on_cost_custom_second:
        by: 'css selector'
        value: 'input.custom_select_input'
    add_on_cost_rate_second:
        by: 'css selector'
        value: '.aoc_value > input[type="number"]'
    add_on_cost_fee_type:
        by: 'css selector'
        value: 'select[id$="_fee_type"]'
    add_on_cost_billable:
        by: 'css selector'
        value: 'input[id$="_billable"]'
    add_on_cost_marketplace:
        by: 'css selector'
        value: 'input[id$="_marketplace"]'
    aoc_remove_button:
        by: 'css selector'
        value: '.remove_add_on_cost'
    private_inventory:
        by: 'css selector'
        value: '#inventory_pools>div>h1>div>span'
    first_private_inventory:
        by: 'css selector'
        value: '#inventory_pools_content>ol>div:nth-child(3)>div>input'
    gateway:
        by: 'css selector'
        value: '#mobile_connection_types>div>h1>div>span'
    enviroment:
        by: 'css selector'
        value: '#mobile_clients>div>h1>div>span'
    environment_websites:
        value: 'flight_mobile_client_ids_0'
    environment_applications:
        value: 'flight_mobile_client_ids_1'
    environment_other:
        value: 'flight_mobile_client_ids_2'
    devices:
        by: 'css selector'
        value: '#mobile_devices>div>h1>div>span'
    devices_filter:
        value: 'filter_mobile_devices'
    designation:
        value: 'filter_designations'
    master_select:
        by: 'css selector'
        value: '.select_all'
    first_manufacturer:
        by: 'css selector'
        value: '.sortable>tbody>tr:nth-child(1)>.selectable>input'
    first_device:
        by: 'css selector'
        value: '.sortable>tbody>tr:nth-child(2)>.selectable>input'
    device_name:
        by: 'css selector'
        value: '.sortable>tbody>tr:nth-child(1)>.name>div'
    os:
        by: 'css selector'
        value: '#mobile_platforms>div>h1>div>span'
    os_available:
        value: 'mobile_platforms_mobile_platforms_all'
    move_selected_os:
        value: 'mv_sel_mobile_platforms_mobile_platforms'
    remove_selected_os:
        value: 'rm_sel_mobile_platforms_mobile_platforms'
    move_all_selected_os:
        value: 'mv_all_sel_mobile_platforms_mobile_platforms'
    remove_all_selected_os:
        value: 'rm_all_sel_mobile_platforms_mobile_platforms'
    os_selected:
        value: 'mobile_platforms_mobile_platforms_selected'
    carrier:
        by: 'css selector'
        value: '#mobile_carriers>div>h1>div>span'
    carrier_available:
        value: 'mobile_carriers_mobile_carriers_all'
    move_selected_carrier:
        value: 'mv_sel_mobile_carriers_mobile_carriers'
    remove_selected_carrier:
        value: 'rm_sel_mobile_carriers_mobile_carriers'
    move_all_selected_carrier:
        value: 'mv_all_sel_mobile_carriers_mobile_carriers'
    remove_all_selected_carrier:
        value: 'rm_all_sel_mobile_carriers_mobile_carriers'
    carrier_selected:
        value: 'mobile_carriers_mobile_carriers_selected'
    inherit_lang_targeting:
        value: 'flight_inherit_language_targeting_true'
    separate_language_targeting:
        value: 'flight_inherit_language_targeting_false'
    lang_targeting_available:
        value: 'target_languages_target_languages_all'
    move_selected_lang:
        value: 'mv_sel_target_languages_target_languages'
    remove_selected_lang:
        value: 'rm_sel_target_languages_target_languages'
    move_all_selected_lang:
        value: 'mv_all_sel_target_languages_target_languages'
    remove_all_selected_lang:
        value: 'rm_all_sel_target_languages_target_languages'
    lang_targeting_selected:
        value: 'target_languages_target_languages_selected'
    lang_targeting:
        by: 'css selector'
        value: '#language_targeting>div>h1>div>span'
    select_first_lang:
        by: 'css selector'
        value: '#target_languages_target_languages_all > option:first-child'
    geographic_targeting:
        by: 'css selector'
        value: '#target_audiences>div>h1>div>span'
    geo_target_region_dropdown:
        value: 'geo_target_type'
    geofenced_file:
        value: 'geohash_group_file'
    geofenced_name:
        value: 'geohash_group_name'
    geofenced_submit:
        value: 'campaign_geohash_submit'
    geotargeting_upload_error:
        by: 'css'
        value: '.upload_error_message'
    geohash_upload_successfully:
        by: 'css selector'
        value: '#geohash_group_upload_status > span'
    geo_target_country_dropdown:
        value: 'flight_geo_target_country_id'
    geo_target_codes_dropdown:
        value: 'flight_geo_target_area_type'
    geo_targeting_file_upload:
        value: 'postal_code_group_file'
    postal_code_group_name_textbox:
        value: 'postal_code_group_name'
    upload_postal_codes_button:
        by: 'css selector'
        value: '.postal_code_group_upload_submit'
    postal_code_list_table:
        value: 'postal_codes_table'
    inherit_geo_targeting:
        by: 'css_selector'
        value: 'flight_inherit_geo_targeting_true'
    separate_geo_targeting:
        value: 'flight_inherit_geo_targeting_false'
    country_available:
        value: 'country_countries_all'
    country_selected:
        value: 'country_countries_selected'
    country_first_select:
        by: 'css selector'
        value: '#country_countries_all > option:first-child'
    move_selected_country:
        value: 'mv_sel_country_countries'
    remove_selected_country:
        value: 'rm_sel_country_countries'
    move_all_selected_country:
        value: 'mv_all_sel_country_countries'
    remove_all_selected_country:
        value: 'rm_all_sel_country_countries'
    blacklist:
        by: 'css selector'
        value: '#blacklist>div>h1>div>span'
    edit_blacklist_link:
        by: 'css selector'
        value: '#blacklist_content > .bootstrap-three > .alert > a'
    whitelist:
        by: 'css selector'
        value: '#whitelist>div>h1>div>span'
    edit_whitelist_link:
        by: 'css selector'
        value: '#whitelist_content > .bootstrap-three > .alert > a'
    audience_targeting:
        by : 'css selector'
        value: '#audience_targeting>div>h1>div>span'
    audience_search:
        by : 'css selector'
        value: '.available>input'
    avail_audience:
        value: 'segments_all'
    included_audience:
        value: 'included_segments_selected'
    excluded_audience:
        value: 'excluded_segments_selected'
    include_audience:
        value: 'mv_sel_included_segments'
    include_all_audience:
        value: 'mv_all_sel_included_segments'
    exclude_audience:
        value: 'mv_sel_excluded_segments'
    exclude_all_audience:
        value: 'mv_all_sel_excluded_segments'
    remove_audience:
        value: 'rm_sel_segments'
    remove_all_audience:
        value: 'rm_all_sel_segments'
    edit_link:
        by: 'link text'
        value: 'Edit'
    flight_details:
        by: 'id'
        value: 'flight_details'
    domains_popup:
        by: 'css'
        value: '.ui-dialog.dialog-500'
    flight_attributes_validation:
        start_date: ''
        end_date: ''
        deafault_bid_usd: ''
        Budget_usd: ''
        alloc: ''        
    save_and_exit:
        by: 'css selector'
        value: "input[value='Save & Exit']"
    save_and_continue:
        by: 'css selector'
        value: "input[value='Save & Continue']"
    preferred_placement:
        value: 'flight_visibility'
    flight_attributes:
        fee_type: 'CPM (USD)'
        preferred_placement: 'Above the fold'
        language_target: 'German'
        country_target: 'Brazil'
        blacklist_url: 'www.google.com'
        whitelist_url: 'www.yahoo.com'
        inventory: 'AppNexus'
    blank_error_message:
        start_date_blank: "Start date can't be blank"
        end_date_blank: "End date can't be blank"
        bid_blank: "Default bid can't be blank"
        budget_blank: "Io budget is not a number"
    negative_error_message:
        bid_negative_error: "The bid must be between 0 and 100.0."
        budget_negative_error: "Io budget must be greater than or equal to 0"
        impression_cap_error: "Impression cap must be greater than or equal to 1"
        frequency_cap_err0r: "Frequency Cap impression count must be greater than or equal to 1"
    alphanumeric_error_message:
        bid_error: "Default bid is not a number"
        budget_error: "Io budget is not a number"
        impression_error: "Impression cap is not a number"
        frequency_error: "Frequency Cap impression count is not a number"
    device_targeting_message: 'You have not specified any device types for targeting! At least one must be selected.'
    no_device_types_message: 'At least one Device Type must be selected'
    inputs:
        deals: 'Technology'
        devices: 'samsung galaxy'
    search_text: 'test-deal'
    platforms: ['Android', 'Blackberry', 'iOS', 'OS X', 'Other', 'S40', 'Symbian/S60', 'Unknown', 'Windows', 'Windows Mobile']
    oneview_warning_popup:
        by: 'css selector'
        value: '.modal-dialog.no-close-button'
    one_view_section_enabled:
        value: 'oneview'
    single_device_enabled:
        value: 'flight_oneview_policy_uid_TdBljmQIbB'
    high_precision_enabled:
        value: 'flight_oneview_policy_uid_TdeSfwhQ3E'
    broad_reach_enabled:
        value: 'flight_oneview_policy_uid_Tdf2yuzHuy'
    one_view_section_disabled:
        by: 'css selector'
        value: 'div[id=oneview][class*=hide]'
    single_device_disabled:
        by: 'css selector'
        value: 'input[id=flight_oneview_policy_uid_TdBljmQIbB][disabled="disabled"]'
    high_precision_disabled:
        by: 'css selector'
        value: 'input[id=flight_oneview_policy_uid_TdeSfwhQ3E][disabled="disabled"]'
    broad_reach_disabled:
        by: 'css selector'
        value: 'input[id=flight_oneview_policy_uid_Tdf2yuzHuy][disabled="disabled"]'
    one_view_policies_disabled: ['single_device_disabled', 'high_precision_disabled', 'broad_reach_disabled']
    oneview_aoc_name:
        by: 'css selector'
        value: '.cols3.aoc_name.break-word'
    oneview_popup_ok:
        by: 'css selector'
        value: '.no-close-button > div:nth-child(3) > button:nth-child(1)'
    oneview_popup_cancel:
        by: 'css selector'
        value: '.no-close-button > div:nth-child(3) > button:nth-child(2)'
    one_view_policies_enabled: ['broad_reach_enabled', 'high_precision_enabled', 'single_device_enabled']
    broad_reach_warning: ['high_precision_enabled', 'single_device_enabled']
    single_device_warning: ['high_precision_enabled', 'broad_reach_enabled']
    flight_detailed_edit_page_title: 'Flight: {0}'
    geo_targeting_warning_message: 'You have not specified any countries for targeting! Targeting will default to all countries unless otherwise specified.'
    geo_targeting_error_message: 'Failure to upload postal codes. Sorry, there was an error uploading postal codes.'
    duplicate_aoc_error: 'Add-on costs names must be unique'
    geofenced_msgs:
        without_header_error: "Failure to upload GeoFence groups. The provided CSV has an invalid header! Expected Header: 'latitude, longitude, precision'"
        valid: '110 recognized.'
    environment_validation_error: 'At least one Environment must be selected'
    blacklist_message_text: 'You can edit Blacklists in the new user interface.'
    whitelist_message_text: 'You can edit Whitelists in the new user interface.'
